class RenombraAisla < ActiveRecord::Migration
  def change
    rename :actividad, :sivel2_gen_actividad
    rename :actividad_rangoedadac, :sivel2_gen_actividad_rangoedadac
    rename :actividadarea, :sivel2_gen_actividadarea
    rename :actividadareas_actividad, :sivel2_gen_actividadareas_actividad
    rename :actividadoficio, :sivel2_gen_actividadoficio
    rename :acto, :sivel2_gen_acto
    rename :actocolectivo, :sivel2_gen_actocolectivo
    rename :anexo, :sivel2_gen_anexo
    rename :anexoactividad, :sivel2_gen_anexoactividad
    rename :antecedente, :sivel2_gen_antecedente
    rename :antecedente_caso, :sivel2_gen_antecedente_caso
    rename :antecedente_comunidad, :sivel2_gen_antecedente_comunidad
    rename :antecedente_victima, :sivel2_gen_antecedente_victima
    rename :caso, :sivel2_gen_caso
    rename :caso_categoria_presponsable, :sivel2_gen_caso_categoria_presponsable
    rename :caso_contexto, :sivel2_gen_caso_contexto
    rename :caso_etiqueta, :sivel2_gen_caso_etiqueta
    rename :caso_ffrecuente, :sivel2_gen_caso_ffrecuente
    rename :caso_fotra, :sivel2_gen_caso_fotra
    rename :caso_frontera, :sivel2_gen_caso_frontera
    rename :caso_presponsable, :sivel2_gen_caso_presponsable
    rename :caso_region, :sivel2_gen_caso_region
    rename :caso_usuario, :sivel2_gen_caso_usuario
    rename :categoria, :sivel2_gen_categoria
    rename :clase, :sivel2_gen_clase
    rename :comunidad_filiacion, :sivel2_gen_comunidad_filiacion
    rename :comunidad_organizacion, :sivel2_gen_comunidad_organizacion
    rename :comunidad_profesion, :sivel2_gen_comunidad_profesion
    rename :comunidad_rangoedad, :sivel2_gen_comunidad_rangoedad
    rename :comunidad_sectorsocial, :sivel2_gen_comunidad_sectorsocial
    rename :comunidad_vinculoestado, :sivel2_gen_comunidad_vinculoestado
    rename :contexto, :sivel2_gen_contexto
    rename :departamento, :sivel2_gen_departamento
    rename :escolaridad, :sivel2_gen_escolaridad
    rename :estadocivil, :sivel2_gen_estadocivil
    rename :etiqueta, :sivel2_gen_etiqueta
    rename :etnia, :sivel2_gen_etnia
    rename :ffrecuente, :sivel2_gen_ffrecuente
    rename :filiacion, :sivel2_gen_filiacion
    rename :fotra, :sivel2_gen_fotra
    rename :frontera, :sivel2_gen_frontera
    rename :grupoper, :sivel2_gen_grupoper
    rename :iglesia, :sivel2_gen_iglesia
    rename :intervalo, :sivel2_gen_intervalo
    rename :maternidad, :sivel2_gen_maternidad
    rename :municipio, :sivel2_gen_municipio
    rename :organizacion, :sivel2_gen_organizacion
    rename :pais, :sivel2_gen_pais
    rename :pconsolidado, :sivel2_gen_pconsolidado
    rename :persona, :sivel2_gen_persona
    rename :persona_trelacion, :sivel2_gen_persona_trelacion
    rename :presponsable, :sivel2_gen_presponsable
    rename :profesion, :sivel2_gen_profesion
    rename :rangoedad, :sivel2_gen_rangoedad
    rename :rangoedadac, :sivel2_gen_rangoedadac
    rename :regimensalud, :sivel2_gen_regimensalud
    rename :region, :sivel2_gen_region
    rename :regionsjr, :sivel2_gen_regionsjr
    rename :sectorsocial, :sivel2_gen_sectorsocial
    rename :supracategoria, :sivel2_gen_supracategoria
    rename :tclase, :sivel2_gen_tclase
    rename :tdocumento, :sivel2_gen_tdocumento
    rename :trelacion, :sivel2_gen_trelacion
    rename :tsitio, :sivel2_gen_tsitio
    rename :tviolencia, :sivel2_gen_tviolencia
    rename :ubicacion, :sivel2_gen_ubicacion
    rename :victima, :sivel2_gen_victima
    rename :victimacolectiva, :sivel2_gen_victimacolectiva
    rename :vinculoestado, :sivel2_gen_vinculoestado
  end
end
