class CreatePais < ActiveRecord::Migration
  def change
    create_table :pais do |t|
      t.string :nombre, limit: 200
      t.string :nombreiso, limit: 200
      t.float :latitud
      t.float :longitud
      t.string :alfa2, limit: 2
      t.string :alfa3, limit: 3
      t.integer :codiso
      t.string :div1, limit: 100
      t.string :div2, limit: 100
      t.string :div3, limit: 100
      t.date :fechacreacion
      t.date :fechadeshabilitacion

      t.timestamps
    end
    reversible do |dir|
      dir.up do
        execute <<-SQL
      -- Fuente de paises y codigos ISO: http://es.wikipedia.org/wiki/ISO_3166-1
      -- La identificación es el código ISO
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (170, 'COLOMBIA', 'COLOMBIA', '-75.0974', '4.7465', 'CO', 'COL', 'DEPARTAMENTO', 'MUNICIPIO', 'CENTRO POBLADO', '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (4, 'AFGANISTÁN', 'AFGANISTAN', NULL, NULL, 'AF', 'AFG', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (8, 'ALBANIA', 'ALBANIA', NULL, NULL, 'AL', 'ALB', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (10, 'ANTÁRTIDA', 'ANTARTIDA', NULL, NULL, 'AQ', 'ATA', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (12, 'ARGELIA', 'ARGELIA', NULL, NULL, 'DZ', 'DZA', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (16, 'SAMOA AMERICANA', 'SAMOA AMERICANA', NULL, NULL, 'AS', 'ASM', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (20, 'ANDORRA', 'ANDORRA', NULL, NULL, 'AD', 'AND', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (24, 'ANGOLA', 'ANGOLA', NULL, NULL, 'AO', 'AGO', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (28, 'ANTIGUA Y BARBUDA', 'ANTIGUA Y BARBUDA', NULL, NULL, 'AG', 'ATG', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (31, 'AZERBAIYÁN', 'AZERBAIYAN', NULL, NULL, 'AZ', 'AZE', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (32, 'ARGENTINA', 'ARGENTINA', NULL, NULL, 'AR', 'ARG', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (36, 'AUSTRALIA', 'AUSTRALIA', NULL, NULL, 'AU', 'AUS', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (40, 'AUSTRIA', 'AUSTRIA', NULL, NULL, 'AT', 'AUT', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (44, 'BAHAMAS', 'BAHAMAS', NULL, NULL, 'BS', 'BHS', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (48, 'BARÉIN', 'BAREIN', NULL, NULL, 'BH', 'BHR', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (50, 'BANGLADÉS', 'BANGLADES', NULL, NULL, 'BD', 'BGD', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (51, 'ARMENIA', 'ARMENIA', NULL, NULL, 'AM', 'ARM', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (52, 'BARBADOS', 'BARBADOS', NULL, NULL, 'BB', 'BRB', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (56, 'BÉLGICA', 'BELGICA', NULL, NULL, 'BE', 'BEL', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (60, 'BERMUDAS', 'BERMUDAS', NULL, NULL, 'BM', 'BMU', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (64, 'BUTÁN', 'BUTAN', NULL, NULL, 'BT', 'BTN', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (68, 'BOLIVIA', 'BOLIVIA, ESTADO PLURINACIONAL DE', NULL, NULL, 'BO', 'BOL', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (70, 'BOSNIA Y HERZEGOVINA', 'BOSNIA Y HERZEGOVINA', NULL, NULL, 'BA', 'BIH', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (72, 'BOTSUANA', 'BOTSUANA', NULL, NULL, 'BW', 'BWA', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (74, 'ISLA BOUVET', 'ISLA BOUVET', NULL, NULL, 'BV', 'BVT', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (76, 'BRASIL', 'BRASIL', NULL, NULL, 'BR', 'BRA', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (84, 'BELICE', 'BELICE', NULL, NULL, 'BZ', 'BLZ', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (86, 'TERRITORIO BRITÁNICO DEL OCÉANO ÍNDICO', 'TERRITORIO BRITANICO DEL OCEANO INDICO', NULL, NULL, 'IO', 'IOT', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (90, 'ISLAS SALOMÓN', 'ISLAS SALOMON', NULL, NULL, 'SB', 'SLB', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (92, 'ISLAS VÍRGENES BRITÁNICAS', 'ISLAS VIRGENES BRITANICAS', NULL, NULL, 'VG', 'VGB', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (96, 'BRUNÉI', 'BRUNEI DARUSSALAM', NULL, NULL, 'BN', 'BRN', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (100, 'BULGARIA', 'BULGARIA', NULL, NULL, 'BG', 'BGR', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (104, 'BIRMANIA', 'MYANMAR nota 1', NULL, NULL, 'MM', 'MMR', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (108, 'BURUNDI', 'BURUNDI', NULL, NULL, 'BI', 'BDI', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (112, 'BIELORRUSIA', 'BIELORRUSIA', NULL, NULL, 'BY', 'BLR', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (116, 'CAMBOYA', 'CAMBOYA', NULL, NULL, 'KH', 'KHM', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (120, 'CAMERÚN', 'CAMERUN', NULL, NULL, 'CM', 'CMR', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (124, 'CANADÁ', 'CANADA', NULL, NULL, 'CA', 'CAN', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (132, 'CABO VERDE', 'CABO VERDE', NULL, NULL, 'CV', 'CPV', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (136, 'ISLAS CAIMÁN', 'ISLAS CAIMAN', NULL, NULL, 'KY', 'CYM', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (140, 'REPÚBLICA CENTROAFRICANA', 'REPUBLICA CENTROAFRICANA', NULL, NULL, 'CF', 'CAF', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (144, 'SRI LANKA', 'SRI LANKA', NULL, NULL, 'LK', 'LKA', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (148, 'CHAD', 'CHAD', NULL, NULL, 'TD', 'TCD', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (152, 'CHILE', 'CHILE', NULL, NULL, 'CL', 'CHL', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (156, 'CHINA', 'CHINA, REPUBLICA POPULAR', NULL, NULL, 'CN', 'CHN', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (158, 'TAIWÁN', 'TAIWAN, PROVINCIA DE CHINA', NULL, NULL, 'TW', 'TWN', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (162, 'ISLA DE NAVIDAD', 'ISLA DE NAVIDAD', NULL, NULL, 'CX', 'CXR', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (166, 'ISLAS COCOS', 'ISLAS COCOS (KEELING)', NULL, NULL, 'CC', 'CCK', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (174, 'COMORAS', 'COMORAS', NULL, NULL, 'KM', 'COM', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (175, 'MAYOTTE', 'MAYOTTE', NULL, NULL, 'YT', 'MYT', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (178, 'REPÚBLICA DEL CONGO', 'CONGO', NULL, NULL, 'CG', 'COG', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (180, 'REPÚBLICA DEMOCRÁTICA DEL CONGO', 'CONGO, LA REPUBLICA DEMOCRATICA DEL', NULL, NULL, 'CD', 'COD', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (184, 'ISLAS COOK', 'ISLAS COOK', NULL, NULL, 'CK', 'COK', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (188, 'COSTA RICA', 'COSTA RICA', NULL, NULL, 'CR', 'CRI', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (191, 'CROACIA', 'CROACIA', NULL, NULL, 'HR', 'HRV', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (192, 'CUBA', 'CUBA', NULL, NULL, 'CU', 'CUB', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (196, 'CHIPRE', 'CHIPRE', NULL, NULL, 'CY', 'CYP', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (203, 'REPÚBLICA CHECA', 'REPUBLICA CHECA', NULL, NULL, 'CZ', 'CZE', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (204, 'BENÍN', 'BENIN', NULL, NULL, 'BJ', 'BEN', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (208, 'DINAMARCA', 'DINAMARCA', NULL, NULL, 'DK', 'DNK', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (212, 'DOMINICA', 'DOMINICA', NULL, NULL, 'DM', 'DMA', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (214, 'REPÚBLICA DOMINICANA', 'REPUBLICA DOMINICANA', NULL, NULL, 'DO', 'DOM', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (218, 'ECUADOR', 'ECUADOR', NULL, NULL, 'EC', 'ECU', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (222, 'EL SALVADOR', 'EL SALVADOR', NULL, NULL, 'SV', 'SLV', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (226, 'GUINEA ECUATORIAL', 'GUINEA ECUATORIAL', NULL, NULL, 'GQ', 'GNQ', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (231, 'ETIOPÍA', 'ETIOPIA', NULL, NULL, 'ET', 'ETH', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (232, 'ERITREA', 'ERITREA', NULL, NULL, 'ER', 'ERI', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (233, 'ESTONIA', 'ESTONIA', NULL, NULL, 'EE', 'EST', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (234, 'ISLAS FEROE', 'ISLAS FEROE', NULL, NULL, 'FO', 'FRO', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (238, 'ISLAS MALVINAS', 'ISLAS FALKLAND ( MALVINAS )', NULL, NULL, 'FK', 'FLK', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (239, 'ISLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR', 'ISLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR', NULL, NULL, 'GS', 'SGS', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (242, 'FIYI', 'FIYI', NULL, NULL, 'FJ', 'FJI', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (246, 'FINLANDIA', 'FINLANDIA', NULL, NULL, 'FI', 'FIN', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (248, 'ÅLAND', 'ISLAS ÅLAND', NULL, NULL, 'AX', 'ALA', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (250, 'FRANCIA', 'FRANCIA', NULL, NULL, 'FR', 'FRA', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (254, 'GUAYANA FRANCESA', 'GUAYANA FRANCESA', NULL, NULL, 'GF', 'GUF', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (258, 'POLINESIA FRANCESA', 'POLINESIA FRANCESA', NULL, NULL, 'PF', 'PYF', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (260, 'TERRITORIOS AUSTRALES FRANCESES', 'TERRITORIOS AUSTRALES FRANCESES', NULL, NULL, 'TF', 'ATF', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (262, 'YIBUTI', 'YIBUTI', NULL, NULL, 'DJ', 'DJI', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (266, 'GABÓN', 'GABON', NULL, NULL, 'GA', 'GAB', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (268, 'GEORGIA', 'GEORGIA', NULL, NULL, 'GE', 'GEO', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (270, 'GAMBIA', 'GAMBIA', NULL, NULL, 'GM', 'GMB', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (275, 'ESTADO DE PALESTINA', 'PALESTINA, ESTADO DE', NULL, NULL, 'PS', 'PSE', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (276, 'ALEMANIA', 'ALEMANIA', NULL, NULL, 'DE', 'DEU', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (288, 'GHANA', 'GHANA', NULL, NULL, 'GH', 'GHA', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (292, 'GIBRALTAR', 'GIBRALTAR', NULL, NULL, 'GI', 'GIB', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (296, 'KIRIBATI', 'KIRIBATI', NULL, NULL, 'KI', 'KIR', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (300, 'GRECIA', 'GRECIA', NULL, NULL, 'GR', 'GRC', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (304, 'GROENLANDIA', 'GROENLANDIA', NULL, NULL, 'GL', 'GRL', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (308, 'GRANADA', 'GRANADA', NULL, NULL, 'GD', 'GRD', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (312, 'GUADALUPE', 'GUADALUPE', NULL, NULL, 'GP', 'GLP', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (316, 'GUAM', 'GUAM', NULL, NULL, 'GU', 'GUM', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (320, 'GUATEMALA', 'GUATEMALA', NULL, NULL, 'GT', 'GTM', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (324, 'GUINEA', 'GUINEA', NULL, NULL, 'GN', 'GIN', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (328, 'GUYANA', 'GUYANA', NULL, NULL, 'GY', 'GUY', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (332, 'HAITÍ', 'HAITI', NULL, NULL, 'HT', 'HTI', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (334, 'ISLAS HEARD Y MCDONALD', 'ISLAS HEARD Y MCDONALD', NULL, NULL, 'HM', 'HMD', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (336, 'CIUDAD DEL VATICANO', 'SANTA SEDE (CIUDAD ESTADO VATICAVO)', NULL, NULL, 'VA', 'VAT', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (340, 'HONDURAS', 'HONDURAS', NULL, NULL, 'HN', 'HND', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (344, 'HONG KONG', 'HONG KONG', NULL, NULL, 'HK', 'HKG', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (348, 'HUNGRÍA', 'HUNGRIA', NULL, NULL, 'HU', 'HUN', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (352, 'ISLANDIA', 'ISLANDIA', NULL, NULL, 'IS', 'ISL', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (356, 'INDIA', 'INDIA', NULL, NULL, 'IN', 'IND', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (360, 'INDONESIA', 'INDONESIA', NULL, NULL, 'ID', 'IDN', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (364, 'IRÁN', 'IRAN, REPUBLICA ISLAMICA DE', NULL, NULL, 'IR', 'IRN', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (368, 'IRAK', 'IRAK', NULL, NULL, 'IQ', 'IRQ', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (372, 'IRLANDA', 'IRLANDA', NULL, NULL, 'IE', 'IRL', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (376, 'ISRAEL', 'ISRAEL', NULL, NULL, 'IL', 'ISR', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (380, 'ITALIA', 'ITALIA', NULL, NULL, 'IT', 'ITA', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (384, 'COSTA DE MARFIL', 'COSTA DE MARFIL', NULL, NULL, 'CI', 'CIV', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (388, 'JAMAICA', 'JAMAICA', NULL, NULL, 'JM', 'JAM', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (392, 'JAPÓN', 'JAPON', NULL, NULL, 'JP', 'JPN', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (398, 'KAZAJISTÁN', 'KAZAJISTAN', NULL, NULL, 'KZ', 'KAZ', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (400, 'JORDANIA', 'JORDANIA', NULL, NULL, 'JO', 'JOR', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (404, 'KENIA', 'KENIA', NULL, NULL, 'KE', 'KEN', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (408, 'COREA DEL NORTE', 'COREA, REPUBLICA DEMOCRATICA POPULAR DE', NULL, NULL, 'KP', 'PRK', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (410, 'COREA DEL SUR', 'COREA, REPUBLICA DE', NULL, NULL, 'KR', 'KOR', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (414, 'KUWAIT', 'KUWAIT', NULL, NULL, 'KW', 'KWT', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (417, 'KIRGUISTÁN', 'KIRGUISTAN', NULL, NULL, 'KG', 'KGZ', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (418, 'LAOS', 'REPUBLICA DEMOCRATICA POPULAR LAO', NULL, NULL, 'LA', 'LAO', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (422, 'LÍBANO', 'LIBANO', NULL, NULL, 'LB', 'LBN', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (426, 'LESOTO', 'LESOTO', NULL, NULL, 'LS', 'LSO', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (428, 'LETONIA', 'LETONIA', NULL, NULL, 'LV', 'LVA', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (430, 'LIBERIA', 'LIBERIA', NULL, NULL, 'LR', 'LBR', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (434, 'LIBIA', 'LIBIA', NULL, NULL, 'LY', 'LBY', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (438, 'LIECHTENSTEIN', 'LIECHTENSTEIN', NULL, NULL, 'LI', 'LIE', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (440, 'LITUANIA', 'LITUANIA', NULL, NULL, 'LT', 'LTU', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (442, 'LUXEMBURGO', 'LUXEMBURGO', NULL, NULL, 'LU', 'LUX', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (446, 'MACAO', 'MACAO', NULL, NULL, 'MO', 'MAC', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (450, 'MADAGASCAR', 'MADAGASCAR', NULL, NULL, 'MG', 'MDG', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (454, 'MALAUI', 'MALAUI', NULL, NULL, 'MW', 'MWI', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (458, 'MALASIA', 'MALASIA', NULL, NULL, 'MY', 'MYS', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (462, 'MALDIVAS', 'MALDIVAS', NULL, NULL, 'MV', 'MDV', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (466, 'MALÍ', 'MALI', NULL, NULL, 'ML', 'MLI', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (470, 'MALTA', 'MALTA', NULL, NULL, 'MT', 'MLT', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (474, 'MARTINICA', 'MARTINICA', NULL, NULL, 'MQ', 'MTQ', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (478, 'MAURITANIA', 'MAURITANIA', NULL, NULL, 'MR', 'MRT', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (480, 'MAURICIO', 'MAURICIO', NULL, NULL, 'MU', 'MUS', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (484, 'MÉXICO', 'MEXICO', NULL, NULL, 'MX', 'MEX', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (492, 'MÓNACO', 'MONACO', NULL, NULL, 'MC', 'MCO', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (496, 'MONGOLIA', 'MONGOLIA', NULL, NULL, 'MN', 'MNG', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (498, 'MOLDAVIA', 'MOLDAVIA, REPUBLICA DE', NULL, NULL, 'MD', 'MDA', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (499, 'MONTENEGRO', 'MONTENEGRO', NULL, NULL, 'ME', 'MNE', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (500, 'MONTSERRAT', 'MONTSERRAT', NULL, NULL, 'MS', 'MSR', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (504, 'MARRUECOS', 'MARRUECOS', NULL, NULL, 'MA', 'MAR', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (508, 'MOZAMBIQUE', 'MOZAMBIQUE', NULL, NULL, 'MZ', 'MOZ', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (512, 'OMÁN', 'OMAN', NULL, NULL, 'OM', 'OMN', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (516, 'NAMIBIA', 'NABIMIA', NULL, NULL, 'NA', 'NAM', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (520, 'NAURU', 'NAURU', NULL, NULL, 'NR', 'NRU', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (524, 'NEPAL', 'NEPAL', NULL, NULL, 'NP', 'NPL', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (528, 'PAÍSES BAJOS', 'PAISES BAJOS', NULL, NULL, 'NL', 'NLD', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (531, 'CURAZAO', 'CURAZAO', NULL, NULL, 'CW', 'CUW', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (533, 'ARUBA', 'ARUBA', NULL, NULL, 'AW', 'ABW', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (534, 'SINT MAARTEN', 'SINT MAARTEN (PARTE NEERLANDESA)', NULL, NULL, 'SX', 'SXM', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (535, 'CARIBE NEERLANDÉS', 'BONAIRE, SAN EUSTAQUIO Y SABA', NULL, NULL, 'BQ', 'BES', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (540, 'NUEVA CALEDONIA', 'NUEVA CALEDONIA', NULL, NULL, 'NC', 'NCL', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (548, 'VANUATU', 'VANUATU', NULL, NULL, 'VU', 'VUT', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (554, 'NUEVA ZELANDA', 'NUEVA ZELANDA', NULL, NULL, 'NZ', 'NZL', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (558, 'NICARAGUA', 'NICARAGUA', NULL, NULL, 'NI', 'NIC', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (562, 'NÍGER', 'NIGER', NULL, NULL, 'NE', 'NER', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (566, 'NIGERIA', 'NIGERIA', NULL, NULL, 'NG', 'NGA', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (570, 'NIUE', 'NIUE', NULL, NULL, 'NU', 'NIU', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (574, 'NORFOLK', 'ISLA NORFOLK', NULL, NULL, 'NF', 'NFK', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (578, 'NORUEGA', 'NORUEGA', NULL, NULL, 'NO', 'NOR', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (580, 'ISLAS MARIANAS DEL NORTE', 'ISLAS MARIANAS DEL NORTE', NULL, NULL, 'MP', 'MNP', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (581, 'ISLAS ULTRAMARINAS DE ESTADOS UNIDOS', 'ISLAS ULTRAMARINAS MENORES DE ESTADOS UNIDOS', NULL, NULL, 'UM', 'UMI', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (583, 'MICRONESIA', 'MICRONESIA, ESTADOS FEDERADOS DE', NULL, NULL, 'FM', 'FSM', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (584, 'ISLAS MARSHALL', 'ISLAS MARSHALL', NULL, NULL, 'MH', 'MHL', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (585, 'PALAOS', 'PALAOS', NULL, NULL, 'PW', 'PLW', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (586, 'PAKISTÁN', 'PAKISTAN', NULL, NULL, 'PK', 'PAK', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (591, 'PANAMÁ', 'PANAMA', NULL, NULL, 'PA', 'PAN', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (598, 'PAPÚA NUEVA GUINEA', 'PAPUA NUEVA GUINEA', NULL, NULL, 'PG', 'PNG', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (600, 'PARAGUAY', 'PARAGUAY', NULL, NULL, 'PY', 'PRY', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (604, 'PERÚ', 'PERU', NULL, NULL, 'PE', 'PER', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (608, 'FILIPINAS', 'FILIPINAS', NULL, NULL, 'PH', 'PHL', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (612, 'ISLAS PITCAIRN', 'PITCAIRN', NULL, NULL, 'PN', 'PCN', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (616, 'POLONIA', 'POLONIA', NULL, NULL, 'PL', 'POL', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (620, 'PORTUGAL', 'PORTUGAL', NULL, NULL, 'PT', 'PRT', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (624, 'GUINEA-BISÁU', 'GUINEA-BISAU', NULL, NULL, 'GW', 'GNB', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (626, 'TIMOR ORIENTAL', 'TIMOR-LESTE', NULL, NULL, 'TL', 'TLS', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (630, 'PUERTO RICO', 'PUERTO RICO', NULL, NULL, 'PR', 'PRI', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (634, 'CATAR', 'QATAR', NULL, NULL, 'QA', 'QAT', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (638, 'REUNIÓN', 'REUNION', NULL, NULL, 'RE', 'REU', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (642, 'RUMANIA', 'RUMANIA', NULL, NULL, 'RO', 'ROU', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (643, 'RUSIA', 'FEDERACION RUSA', NULL, NULL, 'RU', 'RUS', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (646, 'RUANDA', 'RUANDA', NULL, NULL, 'RW', 'RWA', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (652, 'SAN BARTOLOMÉ', 'SAN BARTOLOME', NULL, NULL, 'BL', 'BLM', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (654, 'SANTA HELENA, A. Y T.', 'SANTA HELENA, ASCENSION Y TRISTAN DE ACUÑA', NULL, NULL, 'SH', 'SHN', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (659, 'SAN CRISTÓBAL Y NIEVES', 'SAN CRISTOBAL Y NIEVES', NULL, NULL, 'KN', 'KNA', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (660, 'ANGUILA', 'ANGUILA', NULL, NULL, 'AI', 'AIA', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (662, 'SANTA LUCÍA', 'SANTA LUCIA', NULL, NULL, 'LC', 'LCA', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (663, 'SAN MARTÍN', 'SAN MARTIN (PARTE FRANCESA)', NULL, NULL, 'MF', 'MAF', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (666, 'SAN PEDRO Y MIQUELÓN', 'SAN PEDRO Y MIQUELON', NULL, NULL, 'PM', 'SPM', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (670, 'SAN VICENTE Y LAS GRANADINAS', 'SAN VICENTE Y LAS GRANADINAS', NULL, NULL, 'VC', 'VCT', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (674, 'SAN MARINO', 'SAN MARINO', NULL, NULL, 'SM', 'SMR', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (678, 'SANTO TOMÉ Y PRÍNCIPE', 'SANTO TOME Y PRINCIPE', NULL, NULL, 'ST', 'STP', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (682, 'ARABIA SAUDITA', 'ARABIA SAUDITA', NULL, NULL, 'SA', 'SAU', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (686, 'SENEGAL', 'SENEGAL', NULL, NULL, 'SN', 'SEN', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (688, 'SERBIA', 'SERBIA', NULL, NULL, 'RS', 'SRB', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (690, 'SEYCHELLES', 'SEYCHELLES', NULL, NULL, 'SC', 'SYC', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (694, 'SIERRA LEONA', 'SIERRA LEONA', NULL, NULL, 'SL', 'SLE', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (702, 'SINGAPUR', 'SINGAPUR', NULL, NULL, 'SG', 'SGP', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (703, 'ESLOVAQUIA', 'ESLOVAQUIA', NULL, NULL, 'SK', 'SVK', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (704, 'VIETNAM', 'VIET NAM', NULL, NULL, 'VN', 'VNM', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (705, 'ESLOVENIA', 'ESLOVENIA', NULL, NULL, 'SI', 'SVN', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (706, 'SOMALIA', 'SOMALIA', NULL, NULL, 'SO', 'SOM', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (710, 'SUDÁFRICA', 'SUDAFRICA', NULL, NULL, 'ZA', 'ZAF', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (716, 'ZIMBABUE', 'ZIMBABUE', NULL, NULL, 'ZW', 'ZWE', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (724, 'ESPAÑA', 'ESPAÑA', NULL, NULL, 'ES', 'ESP', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (728, 'SUDÁN DEL SUR', 'SUDAN DEL SUR', NULL, NULL, 'SS', 'SSD', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (729, 'SUDÁN', 'SUDAN', NULL, NULL, 'SD', 'SDN', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (732, 'SAHARA OCCIDENTAL', 'SAHARA OCCIDENTAL', NULL, NULL, 'EH', 'ESH', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (740, 'SURINAM', 'SURINAM', NULL, NULL, 'SR', 'SUR', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (744, 'SVALBARD Y JAN MAYEN', 'SVALBARD Y JAN MAYEN', NULL, NULL, 'SJ', 'SJM', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (748, 'SUAZILANDIA', 'SUAZILANDIA', NULL, NULL, 'SZ', 'SWZ', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (752, 'SUECIA', 'SUECIA', NULL, NULL, 'SE', 'SWE', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (756, 'SUIZA', 'SUIZA', NULL, NULL, 'CH', 'CHE', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (760, 'SIRIA', 'REPUBLICA ARABE DE SIRIA', NULL, NULL, 'SY', 'SYR', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (762, 'TAYIKISTÁN', 'TAYIKISTAN', NULL, NULL, 'TJ', 'TJK', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (764, 'TAILANDIA', 'TAILANDIA', NULL, NULL, 'TH', 'THA', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (768, 'TOGO', 'TOGO', NULL, NULL, 'TG', 'TGO', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (772, 'TOKELAU', 'TOKELAU', NULL, NULL, 'TK', 'TKL', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (776, 'TONGA', 'TONGA', NULL, NULL, 'TO', 'TON', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (780, 'TRINIDAD Y TOBAGO', 'TRINIDAD Y TOBAGO', NULL, NULL, 'TT', 'TTO', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (784, 'EMIRATOS ÁRABES UNIDOS', 'EMIRATOS ARABES UNIDOS', NULL, NULL, 'AE', 'ARE', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (788, 'TÚNEZ', 'TUNEZ', NULL, NULL, 'TN', 'TUN', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (792, 'TURQUÍA', 'TURQUIA', NULL, NULL, 'TR', 'TUR', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (795, 'TURKMENISTÁN', 'TURKMENISTAN', NULL, NULL, 'TM', 'TKM', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (796, 'ISLAS TURCAS Y CAICOS', 'ISLAS TURCAS Y CAICOS', NULL, NULL, 'TC', 'TCA', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (798, 'TUVALU', 'TUVALU', NULL, NULL, 'TV', 'TUV', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (800, 'UGANDA', 'UGANDA', NULL, NULL, 'UG', 'UGA', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (804, 'UCRANIA', 'UCRANIA', NULL, NULL, 'UA', 'UKR', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (807, 'REPÚBLICA DE MACEDONIA', 'MACEDONIA, LA ANTIGUA REPUBLICA YUGOSLAVA DE', NULL, NULL, 'MK', 'MKD', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (818, 'EGIPTO', 'EGIPTO', NULL, NULL, 'EG', 'EGY', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (826, 'REINO UNIDO', 'REINO UNIDO', NULL, NULL, 'GB', 'GBR', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (831, 'GUERNSEY', 'GUERNSEY', NULL, NULL, 'GG', 'GGY', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (832, 'JERSEY', 'JERSEY', NULL, NULL, 'JE', 'JEY', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (833, 'ISLA DE MAN', 'ISLA DE MAN', NULL, NULL, 'IM', 'IMN', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (834, 'TANZANIA', 'TANZANIA, REPUBLICA UNIDA DE', NULL, NULL, 'TZ', 'TZA', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (840, 'ESTADOS UNIDOS', 'ESTADOS UNIDOS', NULL, NULL, 'US', 'USA', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (850, 'ISLAS VÍRGENES DE LOS ESTADOS UNIDOS', 'ISLAS VIRGENES DE LOS ESTADOS UNIDOS', NULL, NULL, 'VI', 'VIR', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (854, 'BURKINA FASO', 'BURKINA FASO', NULL, NULL, 'BF', 'BFA', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (858, 'URUGUAY', 'URUGUAY', NULL, NULL, 'UY', 'URY', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (860, 'UZBEKISTÁN', 'UZBEKISTAN', NULL, NULL, 'UZ', 'UZB', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (862, 'VENEZUELA', 'VENEZUELA, REPUBLICA BOLIVARIANA DE', '-66.2215', '7.7232', 'VE', 'VEN', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (882, 'SAMOA', 'SAMOA', NULL, NULL, 'WS', 'WSM', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (887, 'YEMEN', 'YEMEN', NULL, NULL, 'YE', 'YEM', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
      INSERT INTO pais (id, nombre, nombreiso, latitud, longitud, alfa2, alfa3, div1, div2, div3, fechacreacion, fechadeshabilitacion, created_at, updated_at) VALUES (894, 'ZAMBIA', 'ZAMBIA', NULL, NULL, 'ZM', 'ZMB', NULL, NULL, NULL, '2014-02-17', NULL, NULL, NULL);
        SQL
      end
    end
  end
end
